Repository openshift/cloud-network-config-controller, pull requests merged in 2022-07, with the labels that each got.

#48 Bug 2105996: Fix assign error display for cloudprivateipconfig
  pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
Labels: lgtm, approved, bugzilla/severity-low, bugzilla/valid-bug

#51 Update OWNERS
  OWNERS
Labels: lgtm, approved

#50 Bug 2104784: AWS: Fix race in IP address assignment code
  pkg/cloudprovider/aws.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug
