Repository openshift/cloud-network-config-controller, pull requests merged in 2022-12, with the labels that each got.

#83 [release-4.11] OCPBUGS-4163: AWS: Fix race in IP address assignment code
  pkg/cloudprovider/aws.go
Labels: lgtm, cherry-pick-approved, approved, bugzilla/valid-bug, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#79 [release-4.11] OCPBUGS-4167: Run azure operations in sequence
  pkg/cloudprovider/azure.go
  pkg/cloudprovider/cloudprovider.go
Labels: lgtm, cherry-pick-approved, approved, bugzilla/valid-bug, backport-risk-assessed, jira/severity-important, jira/valid-bug

#77 OCPBUGS-3993: OpenStack: Only return egressIPConfiguration for first InternalIP
  pkg/cloudprovider/openstack.go
  pkg/cloudprovider/openstack_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#87 OCPBUGS-4724: OpenStack: Support multi AZ environments
  pkg/cloudprovider/openstack.go
  pkg/cloudprovider/openstack_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#90 Fix typos in README.md
  README.md
Labels: lgtm, approved

#91 Add ApplicationSecurityGroups to InterfaceIPConfiguration
  pkg/cloudprovider/azure.go
Labels: lgtm, approved
