Repository openshift/cloud-network-config-controller, pull requests merged in 2022-10, with the labels that each got.

#65 Update .ci-operator.yaml to use go 1.19
  .ci-operator.yaml
Labels: lgtm, approved

#68 OCPBUGS-1417: AWS: build temp credentials file from AWS key and secret
  pkg/cloudprovider/aws.go
  pkg/cloudprovider/aws_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#62 OCPBUGS-1736: use proxy vars when available
  pkg/cloudprovider/openstack.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug
