Repository openshift/cloud-network-config-controller, pull requests merged in 2022-04, with the labels that each got.

#32 Bug 2072439: Get subnet information from subnet instead of from network addresses
  pkg/cloudprovider/azure.go
Labels: lgtm, approved, bugzilla/severity-low, bugzilla/valid-bug

#31 Add instructions for how to run image in cloud
  README.md
  hack/run_in_cloud.sh
Labels: lgtm, approved

#36 Bug 2071914: azure: default empty environment to AzurePublicCloud
  cmd/cloud-network-config-controller/main.go
  pkg/cloudprovider/azure.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug
