Repository openshift/cloud-network-config-controller, pull requests merged in 2022-08, with the labels that each got.

#52 Bug 2111878: Make azure operations to be in sequence
  pkg/cloudprovider/azure.go
  pkg/cloudprovider/cloudprovider.go
Labels: lgtm, approved, bugzilla/severity-low, bugzilla/valid-bug

#53 Bug 2118563: Adjust OpenStack port capacity to default max_allowed_address_pair
  pkg/cloudprovider/openstack.go
  pkg/cloudprovider/openstack_test.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#55 Jira OCPBUGS-247: OpenStack Return UnexpectedURIError when URI cannot be parsed
  pkg/cloudprovider/openstack.go
  pkg/cloudprovider/openstack_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#54 Jira OCPBUGS-208: OpenStack: Avoid concurrent port updates for attach/detach operations
  pkg/cloudprovider/openstack.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug
