Repository openshift/cloud-network-config-controller, pull requests merged in 2024-04, with the labels that each got.

#134 OCPBUGS-30146: Serialize scheme construction to prevent panic
  cmd/cloud-network-config-controller/main.go
  pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#133 OCPBUGS-27422: Avoid nil pointer panic while assigning private IP on Azure
  pkg/cloudprovider/azure.go
Labels: lgtm, ok-to-test, approved, jira/valid-bug, jira/valid-reference

#136 OCPBUGS-29915: GCP: Explicitly set UniverseDomain to the default universe domain
  pkg/cloudprovider/gcp.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
