Repository openshift/cloud-network-config-controller, pull requests merged in 2025-04, with the labels that each got.

#167 OSASINFRA-3755: Prefer CA cert from credentials secret
  README.md
  pkg/cloudprovider/openstack.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#169 CNTRLPLANE-112: Remove ARO HCP MIv2 authentication from CNCC
  go.mod
  pkg/cloudprovider/azure.go
  pkg/filewatcher/filewatcher.go
Labels: lgtm, approved, jira/valid-reference

#168 OCPBUGS-45891: Increase API call timeout to 30 second
  pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
  pkg/controller/controller.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
